language: cpp

compiler:
  - clang

script: rake ci

branches:
  only:
    - master
    - short_type_names

before_install:
  - git clone https://github.com/PhilCK/CppUnitTester.git unit_test
  - pip install codecov

after_success:
  - codecov